### ISSUE TITLE
Criar model conexão

### ISSUE THREAD

**Issue by VitinGroot** [guilherme-adesouza/linguini#16]
*Tempo estimado: 10 minutos*

Esta classe será criada para não permitir mais de uma conexão.

**Comment by guilherme-adesouza** [comment]
Rejeita, pois a conexão com banco de dados vai ser feita a partir de cada requisição, sendo fechada após o término da mesma. Ao contrário da proposta desta tarefa, onde a ficaria aberta até o término da execução do programa.
