### ISSUE TITLE
Criar tela principal

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/linguini#2]
*Tempo estimado: 1 hora*

Após fazer o login, o usuário irá visualizar a tela principal. A estrutura dela deverá ser uma barra de menu no parte superior da tela, numa disposição de abas, onde para cada opção, como Produtos, abrirá as opções relacionadas.

Menus sugeridos:
- Cliente
- Pedido
- Produto
- Financeiro
- Relatórios
- ...

Além disso, tambeḿ teremos um menu lateral para as opções mais importantes para o usuário. Este vai ser disposto com ícones grandes, a princípio sem labels para representar a ação do mesmo, pois a imagem deve ser autoexplicativa.

Opções sugeridas:
- Pedido
- Cliente
- Delivery
- Produto
- Financeiro
- Sair

Rascunho de protótipo da tela principal:

![RASCUNHO](https://user-images.githubusercontent.com/34776257/43689487-d9f93836-98d1-11e8-9681-81f398ea20df.png)

**Comment by VitinGroot** [comment]
Tempo de execução: 3 horas
