### ISSUE TITLE
Criar tela de login

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/linguini#3]
*Tempo estimado: 1 hora*

Criar tela de login para fazer acesso ao sistema.

A tela deve conter o campo para informar nome do usuário e senha, além do botão de login. Caso não exista usuário ou a senha não for correta, mostrar tela de erro (Dialog) : "Usuário ou senha incorretos".

**Comment by VitinGroot** [comment]
Tempo de execução: 1 hora
