### ISSUE TITLE
Tela Pedido

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/linguini#35]
*Tempo estimado: 4 horas*

Permitir o usuário fazer as operações básicas de CRUD com o objeto Pedido. 

RNFs:
- Os itens disponíveis poderão ser pesquisados através de um campo de busca simples dentro da própria tela, sendo exibidos as opções dentro de uma caixa de sugestões juntamente ao campo de busca, como um campo de pesquisa web.

- O objeto atendente será populado automaticamente e ficará desabilitado para edição, caso apareça na tela

As outras regras de negócio que surgirem serão informadas nesta mesma tarefa

**Comment by VitinGroot** [comment]
Tempo: 10 Horas
