### ISSUE TITLE
CRUD Pedido

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/linguini#36]
*Tempo estimado: 6 horas*

Criação do CRUD do objeto Pedido, assim como suas validações e métodos. 
Os cálculos de desconto, inserções de produtos, e outras operações do objeto *NÃO DEVEM* ser feitas na tela do pedido, e sim dentro da MODEL.

**Comment by VitinGroot** [comment]
Tempo: 20 Horas
