### ISSUE TITLE
Artefatos relativos ao BD

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/linguini#38]
Tempo estimado: 8 horas`

Implementar 
- [ ] 5 funções em banco de dados
- [ ] 5 outros recursos em banco de dados: gatilhos, visões, cursores

Ao executar cada uma dessas funções de BD, colocar no em arquivo SQL na aplicação e documentar a utilidade do mesmo, tanto no arquivo como nesta tarefa.

Ex:
`--Comando para criar uma tabela no BD`
`CREATE TABLE`

**Comment by VitinGroot** [comment]
#Tempo: 4 Horas
