### ISSUE TITLE
Geração de Gráficos para Dashboard

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/linguini#46]
Construir uma tela para exibição de gráficos, formando assim uma espécie de Dashboard.

Esta tela deve ser permitir os filtros de dados importantes da aplicação, como venda e financeiro, onde o usuário irá montar os filtros desejados e poderá gerar um gráfico, seja ele de linhas, barras, pizza, etc, ou gerar um relatório sobre o mesmo.

A geração efeiva do relatório será implementada em um segundo momento.

**OBS: Lembrar de importar as bibliotecas na pasta libs**

**Comment by VitinGroot** [comment]
#Tempo: 6 horas
