### ISSUE TITLE
Instalador do sistema

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/linguini#49]
*Tempo estimado: 6 horas*

Criar um instalador para a aplicação (não é necessário desenvolver/implementar o instalador, usem um pronto). Deve ser contemplada a instalação de uma aplicação do zero, como também a atualização de uma versão.
Fazem parte de um instalador: arquivos de sistema, arquivos de configuração, scripts de BD e demais.

Com processo ideal, sugere-se fazer backup da versão instalada e então atualizar. Em caso de erro, retornar versão estável (anterior). A aplicação deve estar funcional fora do ambiente de programação, ou seja, está instalada em um diretório /sistema.

As atividades do instalador devem gerar registro de Log quando forem executadas.

**Comment by VitinGroot** [comment]
Tempo: 2 Horas
