### ISSUE TITLE
Controle de Licenciamento

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/linguini#51]
O objetivo dessa implementação é controlar o uso do sistema por meio de uma licença que possui prazo de validade. Os clientes adquirem o sistema e possuem um plano mensal (normalmente). Para cada contrato de sistema, a validade costuma ser definida, ou seja, existe uma data em que o sistema deixa de funcionar. Para evitar isso, o cliente paga a nova mensalidade e recebe uma nova licença para um novo período. O acesso ao sistema com licença vencida, bloqueia o login.

Criar uma lógica para manter e verificar a licença de uso da aplicação. A licença acaba sendo, nada mais e nada menos, que um arquivo (quando a troca de dados ocorrer nesse formato) contendo informações como: dados do cliente, tipo de licença e validade (data específica). O foco em nosso caso é a data em si. Para evitar que o próprio cliente burle esse processo, os dados desse arquivo são ilegíveis (leia-se criptografados), sendo possível decodificação apenas pelo sistema.

Dessa forma, o licenciamento pode ser feito por meio de um arquivo (variações são aceitas) que fica na pasta do sistema. A cada mês um novo arquivo é recebido, ele pode chegar por e-mail e alguém 'coloca ele à mão na pasta'.
Toda vez que o sistema for aberto, é verificada licença de uso. O sistema deve começar a emitir aviso após o login a partir 5 dias antes da licença vencer até o último dia. Licença vencida, exibe mensagem informativa e bloqueia acesso.

**Comment by VitinGroot** [comment]
Tempo: 2 Horas
