### ISSUE TITLE
Criação da tela de fluxo de caixa

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/linguini#8]
*Tempo estimado: 1 hora*

Criação da tela para o fluxo do caixa, permitindo o usuário lançar uma quantidade inicial para o movimento do caixa, assim como encerrar o mesmo, sendo esse fluxo, geralmente, de padrão diário.

OBS: Ainda não temos esta tabela mapeada no banco de dados. Está tarefa gerará outra relacionada.

**Comment by VitinGroot** [comment]
Tempo de execução: 1 Hora
